/*
 * Created on 2023-06-14 ( 09:06:03 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package duan.sportify.entities;

import java.io.Serializable;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * JPA entity class for "Field"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name = "field", catalog = "sportify")
public class Field implements Serializable {

    private static final long serialVersionUID = 1L;

    // --- ENTITY PRIMARY KEY
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "fieldid", nullable = false)
    private Integer fieldid;

    // --- ENTITY DATA FIELDS
    @NotBlank(message = "{NotBlank.field.namefield}")
    @Size(max = 50, message = "{Size.field.namefield}")
    @Column(name = "namefield", nullable = false, length = 50)
    private String namefield;

    @NotBlank(message = "{NotBlank.field.descriptionfield}")
    @Column(name = "descriptionfield", length = 2000)
    private String descriptionfield;

    @Min(value = 0, message = "{Min.field.price}")
    @NotNull(message = "{NotNull.field.price}")
    @Column(name = "price", nullable = false)
    private Double price;

    @Column(name = "image", length = 100)
    private String image;

    @NotBlank(message = "{NotBlank.field.address}")
    @Column(name = "address", nullable = false, length = 200)
    private String address;

    @Column(name = "status")
    private Boolean status;

    @Column(name = "latitude")
    private Double latitude;

    @Column(name = "longitude")
    private Double longitude;

    @Column(name = "available_shifts", length = 500)
    private String availableShifts; // JSON array of shift IDs, e.g., "[1,2,3,4,5]"

    @Column(name = "start_date")
    private String startDate; // Ngày bắt đầu hoạt động

    @Column(name = "end_date")
    private String endDate; // Ngày kết thúc hoạt động

    // --- ENTITY RELATIONSHIP
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "sporttypeid", nullable = false) // JPA sẽ tự map FK
    @JsonIgnoreProperties({ "hibernateLazyInitializer", "handler" })
    private Sporttype sporttype;

    @JsonIgnore
    @OneToMany(mappedBy = "field")
    private List<Bookingdetails> listOfBookingdetails;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "owner_id")
    @JsonIgnoreProperties({ "hibernateLazyInitializer", "handler" })
    private FieldOwnerRegistration owner;
}
