/*
 * Created on 2023-06-14 ( 09:06:03 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package duan.sportify.entities;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;


import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.Getter;
import lombok.Setter;

/**
 * JPA entity class for "Orderdetails"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name = "orderdetails", catalog = "sportify")
public class Orderdetails implements Serializable {

	private static final long serialVersionUID = 1L;



	
	
//    //--- ENTITY PRIMARY KEY 
   @Id
   @GeneratedValue(strategy=GenerationType.IDENTITY)
   @Column(name="orderdetailsid", nullable=false)
   private Integer    orderdetailsid ;
//
   //--- ENTITY DATA FIELDS 

   @Column(name="price", nullable=false)
   private Double     price ;

   @Column(name="quantity", nullable=false)
   private Double    quantity ;
//
//    //--- ENTITY LINKS ( RELATIONSHIP )
   
   @ManyToOne
   @JoinColumn(name="orderid", referencedColumnName="orderid")
    Orders     orders ; 
   @ManyToOne
   @JoinColumn(name="productid", referencedColumnName="productid")
    Products   products ; 


}
