/*
 * Created on 2023-06-14 ( 09:06:03 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package duan.sportify.entities;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.Email;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name = "users", catalog = "sportify")
@JsonIgnoreProperties({ "hibernateLazyInitializer", "handler" })
public class Users implements Serializable {

    private static final long serialVersionUID = 1L;

    // --- ENTITY PRIMARY KEY
    @Id
    @Column(name = "username", nullable = false, length = 16)
    @NotBlank(message = "{NotBlank.users.username}")
    @Size(min = 6, max = 15, message = "{Size.users.username}")
    private String username;

    // --- ENTITY DATA FIELDS
    @Column(name = "passwords", nullable = false, length = 16)
    @NotBlank(message = "{NotBlank.users.passwords}")
    @Size(min = 6, max = 15, message = "{Size.users.passwords}")
    private String passwords;

    @Column(name = "firstname", length = 50)
    @NotBlank(message = "{NotBlank.users.firstname}")
    @Pattern(regexp = "^[\\p{L} ]+$", message = "{Pattern.users.firstname}")
    @Size(max = 50, message = "{Size.users.firstname}")
    private String firstname;

    @Column(name = "lastname", length = 50)
    @NotBlank(message = "{NotBlank.users.lastname}")
    @Pattern(regexp = "^[\\p{L} ]+$", message = "{Pattern.users.lastname}")
    @Size(max = 50, message = "{Size.users.lastname}")
    private String lastname;

    @Column(name = "phone", nullable = false, length = 15)
    @NotBlank(message = "{NotBlank.users.phone}")
    @Pattern(regexp = "^(0|\\+84)\\d{9,10}$", message = "{Pattern.users.phone}")
    private String phone;

    @Column(name = "email", length = 50)
    @NotBlank(message = "{NotBlank.users.email}")
    @Email(message = "{Email.users.email}")
    private String email;

    @Column(name = "address", length = 100)
    @NotBlank(message = "{NotBlank.users.address}")
    private String address;

    @Column(name = "image", length = 50)
    private String image;

    @Column(name = "gender")
    private Boolean gender;

    @Column(name = "status")
    private Boolean status;

    @Column(name = "failed_attempt", columnDefinition = "INT DEFAULT 0")
    private Integer failedAttempt = 0;

    @Column(name = "locked_until")
    private LocalDateTime lockedUntil = null;

    // --- ENTITY LINKS ( RELATIONSHIP )
    @JsonIgnore
    @OneToMany(mappedBy = "users", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<Teamdetails> listOfTeamdetails;

    @JsonIgnore
    @OneToMany(mappedBy = "users", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<Orders> listOfOrders;

    @JsonIgnore
    @OneToMany(mappedBy = "users", cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.EAGER)
    private List<Authorized> listOfAuthorized;

    @JsonIgnore
    @OneToMany(mappedBy = "users", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<Bookings> listOfBookings;

    @JsonIgnore
    @OneToMany(mappedBy = "users", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<Teams> listOfTeams;

    @JsonIgnore
    @OneToMany(mappedBy = "users", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<Contacts> listOfContact;

}
